// frontend/src/components/DevTools.tsx
/**
 * 开发工具组件
 * 提供开发环境下的调试和监控功能
 */

import React, { useState, useEffect } from 'react';
import ApiMonitorPanel from './ApiMonitorPanel';
import { apiMonitor } from '../api/monitor';

interface DevToolsProps {
  enabled?: boolean;
}

const DevTools: React.FC<DevToolsProps> = ({ enabled = process.env.NODE_ENV === 'development' }) => {
  const [isVisible, setIsVisible] = useState(false);
  const [showMonitorPanel, setShowMonitorPanel] = useState(false);
  const [realTimeStats, setRealTimeStats] = useState({
    requestsPerMinute: 0,
    averageResponseTime: 0,
    errorRate: 0,
  });
  const [keySequence, setKeySequence] = useState<string[]>([]);

  // 快捷键序列：Ctrl+Shift+D
  useEffect(() => {
    if (!enabled) return;

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.ctrlKey && event.shiftKey && event.key === 'D') {
        event.preventDefault();
        setIsVisible(prev => !prev);
      }

      // 隐藏快捷键：Escape
      if (event.key === 'Escape') {
        setIsVisible(false);
        setShowMonitorPanel(false);
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [enabled]);

  // 实时更新统计信息
  useEffect(() => {
    if (!enabled || !isVisible) return;

    const updateStats = () => {
      const metrics = apiMonitor.getRealTimeMetrics();
      setRealTimeStats(metrics);
    };

    updateStats();
    const interval = setInterval(updateStats, 1000);
    return () => clearInterval(interval);
  }, [enabled, isVisible]);

  const handleClearCache = () => {
    // 清除所有缓存
    if ('caches' in window) {
      caches.keys().then(names => {
        names.forEach(name => {
          caches.delete(name);
        });
      });
    }
    
    // 清除localStorage中的缓存
    Object.keys(localStorage).forEach(key => {
      if (key.startsWith('api_cache_')) {
        localStorage.removeItem(key);
      }
    });
    
    alert('缓存已清除');
  };

  const handleReloadApp = () => {
    window.location.reload();
  };

  const handleToggleMonitoring = () => {
    const isEnabled = apiMonitor.config?.enabled ?? true;
    apiMonitor.setEnabled(!isEnabled);
    alert(`API监控已${!isEnabled ? '启用' : '禁用'}`);
  };

  const getStatusIndicator = () => {
    if (realTimeStats.errorRate > 5) return '🔴';
    if (realTimeStats.averageResponseTime > 1000) return '🟡';
    return '🟢';
  };

  if (!enabled) return null;

  return (
    <>
      {/* 浮动工具栏 */}
      {isVisible && (
        <div className="fixed bottom-4 right-4 z-50">
          <div className="bg-gray-800 text-white rounded-lg shadow-xl p-4 min-w-80">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold">开发工具</h3>
              <button
                onClick={() => setIsVisible(false)}
                className="text-gray-300 hover:text-white"
              >
                ✕
              </button>
            </div>

            {/* 实时状态 */}
            <div className="mb-4 p-3 bg-gray-700 rounded">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm font-medium">API状态</span>
                <span className="text-lg">{getStatusIndicator()}</span>
              </div>
              <div className="grid grid-cols-3 gap-2 text-xs">
                <div>
                  <div className="text-gray-300">请求/分钟</div>
                  <div className="font-medium">{realTimeStats.requestsPerMinute}</div>
                </div>
                <div>
                  <div className="text-gray-300">平均响应</div>
                  <div className="font-medium">{realTimeStats.averageResponseTime.toFixed(0)}ms</div>
                </div>
                <div>
                  <div className="text-gray-300">错误率</div>
                  <div className="font-medium">{realTimeStats.errorRate.toFixed(1)}%</div>
                </div>
              </div>
            </div>

            {/* 工具按钮 */}
            <div className="space-y-2">
              <button
                onClick={() => setShowMonitorPanel(true)}
                className="w-full bg-blue-600 hover:bg-blue-700 text-white py-2 px-4 rounded text-sm"
              >
                📊 API监控面板
              </button>
              
              <button
                onClick={handleToggleMonitoring}
                className="w-full bg-purple-600 hover:bg-purple-700 text-white py-2 px-4 rounded text-sm"
              >
                🔍 切换API监控
              </button>
              
              <button
                onClick={handleClearCache}
                className="w-full bg-yellow-600 hover:bg-yellow-700 text-white py-2 px-4 rounded text-sm"
              >
                🗑️ 清除缓存
              </button>
              
              <button
                onClick={handleReloadApp}
                className="w-full bg-green-600 hover:bg-green-700 text-white py-2 px-4 rounded text-sm"
              >
                🔄 重新加载
              </button>
              
              <div className="pt-2 border-t border-gray-600">
                <div className="text-xs text-gray-300 space-y-1">
                  <div>快捷键:</div>
                  <div>• Ctrl+Shift+D: 切换工具栏</div>
                  <div>• Escape: 关闭面板</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* 状态指示器（当工具栏隐藏时显示） */}
      {!isVisible && (
        <div 
          className="fixed bottom-4 right-4 z-40 cursor-pointer"
          onClick={() => setIsVisible(true)}
          title="点击打开开发工具 (Ctrl+Shift+D)"
        >
          <div className="bg-gray-800 text-white rounded-full w-12 h-12 flex items-center justify-center shadow-lg hover:bg-gray-700 transition-colors">
            <span className="text-lg">{getStatusIndicator()}</span>
          </div>
        </div>
      )}

      {/* API监控面板 */}
      <ApiMonitorPanel
        isVisible={showMonitorPanel}
        onClose={() => setShowMonitorPanel(false)}
      />
    </>
  );
};

export default DevTools;

// frontend/src/components/DevTools.vue
<template>
  <!-- 状态指示器（当工具栏隐藏时显示） -->
  <div 
    v-if="enabled && !isVisible"
    class="dev-tools-indicator"
    @click="toggleVisibility"
    :title="`点击打开开发工具 (Ctrl+Shift+D)`"
  >
    <div class="indicator-circle">
      <span class="status-emoji">{{ statusIndicator }}</span>
    </div>
  </div>

  <!-- 浮动工具栏 -->
  <div v-if="enabled && isVisible" class="dev-tools-panel">
    <div class="panel-content">
      <div class="panel-header">
        <h3 class="panel-title">开发工具</h3>
        <n-button quaternary circle @click="toggleVisibility">
          <template #icon>
            <n-icon><CloseOutline /></n-icon>
          </template>
        </n-button>
      </div>

      <!-- 实时状态 -->
      <div class="status-section">
        <div class="status-header">
          <span class="status-label">API状态</span>
          <span class="status-indicator-large">{{ statusIndicator }}</span>
        </div>
        <div class="metrics-grid">
          <div class="metric-item">
            <div class="metric-label">请求/分钟</div>
            <div class="metric-value">{{ realTimeStats.requestsPerMinute }}</div>
          </div>
          <div class="metric-item">
            <div class="metric-label">平均响应</div>
            <div class="metric-value">{{ realTimeStats.averageResponseTime.toFixed(0) }}ms</div>
          </div>
          <div class="metric-item">
            <div class="metric-label">错误率</div>
            <div class="metric-value">{{ realTimeStats.errorRate.toFixed(1) }}%</div>
          </div>
        </div>
      </div>

      <!-- 工具按钮 -->
      <div class="tools-section">
        <n-button 
          type="primary" 
          block 
          @click="showMonitorPanel = true"
          class="tool-button"
        >
          <template #icon>
            <n-icon><BarChartOutline /></n-icon>
          </template>
          API监控面板
        </n-button>
        
        <n-button 
          type="info" 
          block 
          @click="toggleMonitoring"
          class="tool-button"
        >
          <template #icon>
            <n-icon><SearchOutline /></n-icon>
          </template>
          切换API监控
        </n-button>
        
        <n-button 
          type="warning" 
          block 
          @click="clearCache"
          class="tool-button"
        >
          <template #icon>
            <n-icon><TrashOutline /></n-icon>
          </template>
          清除缓存
        </n-button>
        
        <n-button 
          type="success" 
          block 
          @click="reloadApp"
          class="tool-button"
        >
          <template #icon>
            <n-icon><RefreshOutline /></n-icon>
          </template>
          重新加载
        </n-button>
        
        <div class="shortcuts-info">
          <div class="shortcuts-title">快捷键:</div>
          <div class="shortcut-item">• Ctrl+Shift+D: 切换工具栏</div>
          <div class="shortcut-item">• Escape: 关闭面板</div>
        </div>
      </div>
    </div>
  </div>

  <!-- API监控面板 -->
  <ApiMonitorPanel 
    v-model:visible="showMonitorPanel"
    @close="showMonitorPanel = false"
  />
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import { NButton, NIcon, useMessage } from 'naive-ui'
import { 
  CloseOutline, 
  BarChartOutline, 
  SearchOutline, 
  TrashOutline, 
  RefreshOutline 
} from '@vicons/ionicons5'
import ApiMonitorPanel from './ApiMonitorPanel.vue'
import { apiMonitor } from '../api/monitor'

interface DevToolsProps {
  enabled?: boolean
}

const props = withDefaults(defineProps<DevToolsProps>(), {
  enabled: import.meta.env.DEV // 开发环境默认启用
})

const message = useMessage()

// 响应式状态
const isVisible = ref(false)
const showMonitorPanel = ref(false)
const realTimeStats = ref({
  requestsPerMinute: 0,
  averageResponseTime: 0,
  errorRate: 0,
})

// 计算属性
const statusIndicator = computed(() => {
  if (realTimeStats.value.errorRate > 5) return '🔴'
  if (realTimeStats.value.averageResponseTime > 1000) return '🟡'
  return '🟢'
})

// 方法
const toggleVisibility = () => {
  isVisible.value = !isVisible.value
}

const updateStats = () => {
  if (!props.enabled || !isVisible.value) return
  
  try {
    const metrics = apiMonitor.getRealTimeMetrics()
    realTimeStats.value = metrics
  } catch (error) {
    console.warn('获取API监控数据失败:', error)
  }
}

const clearCache = async () => {
  try {
    // 清除所有缓存
    if ('caches' in window) {
      const names = await caches.keys()
      await Promise.all(names.map(name => caches.delete(name)))
    }
    
    // 清除localStorage中的缓存
    Object.keys(localStorage).forEach(key => {
      if (key.startsWith('api_cache_')) {
        localStorage.removeItem(key)
      }
    })
    
    message.success('缓存已清除')
  } catch (error) {
    message.error('清除缓存失败')
    console.error('清除缓存失败:', error)
  }
}

const reloadApp = () => {
  window.location.reload()
}

const toggleMonitoring = () => {
  try {
    const config = apiMonitor.getConfig()
    const isEnabled = config.enabled
    apiMonitor.setEnabled(!isEnabled)
    message.success(`API监控已${!isEnabled ? '启用' : '禁用'}`)
  } catch (error) {
    message.error('切换监控状态失败')
    console.error('切换监控状态失败:', error)
  }
}

// 键盘事件处理
const handleKeyDown = (event: KeyboardEvent) => {
  if (!props.enabled) return
  
  if (event.ctrlKey && event.shiftKey && event.key === 'D') {
    event.preventDefault()
    toggleVisibility()
  }
  
  if (event.key === 'Escape') {
    isVisible.value = false
    showMonitorPanel.value = false
  }
}

// 定时器
let statsInterval: number | null = null

// 生命周期
onMounted(() => {
  if (!props.enabled) return
  
  document.addEventListener('keydown', handleKeyDown)
  
  // 启动统计更新
  statsInterval = window.setInterval(updateStats, 1000)
})

onUnmounted(() => {
  document.removeEventListener('keydown', handleKeyDown)
  
  if (statsInterval) {
    clearInterval(statsInterval)
  }
})

// 监听可见性变化
watch(isVisible, (newValue) => {
  if (newValue) {
    updateStats()
  }
})
</script>

<style scoped>
.dev-tools-indicator {
  position: fixed;
  bottom: 16px;
  right: 16px;
  z-index: 1000;
  cursor: pointer;
}

.indicator-circle {
  width: 48px;
  height: 48px;
  background: rgba(0, 0, 0, 0.8);
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
  transition: all 0.3s ease;
}

.indicator-circle:hover {
  background: rgba(0, 0, 0, 0.9);
  transform: scale(1.1);
}

.status-emoji {
  font-size: 18px;
}

.dev-tools-panel {
  position: fixed;
  bottom: 16px;
  right: 16px;
  z-index: 1001;
  width: 320px;
}

.panel-content {
  background: white;
  border-radius: 12px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.2);
  border: 1px solid #e0e0e0;
  overflow: hidden;
}

.panel-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px;
  background: #f8f9fa;
  border-bottom: 1px solid #e0e0e0;
}

.panel-title {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
  color: #333;
}

.status-section {
  padding: 16px;
  background: #f8f9fa;
  border-bottom: 1px solid #e0e0e0;
}

.status-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
}

.status-label {
  font-size: 14px;
  font-weight: 500;
  color: #666;
}

.status-indicator-large {
  font-size: 20px;
}

.metrics-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 8px;
}

.metric-item {
  text-align: center;
}

.metric-label {
  font-size: 11px;
  color: #888;
  margin-bottom: 2px;
}

.metric-value {
  font-size: 14px;
  font-weight: 600;
  color: #333;
}

.tools-section {
  padding: 16px;
}

.tool-button {
  margin-bottom: 8px;
}

.tool-button:last-of-type {
  margin-bottom: 16px;
}

.shortcuts-info {
  padding-top: 12px;
  border-top: 1px solid #e0e0e0;
}

.shortcuts-title {
  font-size: 12px;
  font-weight: 500;
  color: #666;
  margin-bottom: 4px;
}

.shortcut-item {
  font-size: 11px;
  color: #888;
  margin-bottom: 2px;
}

/* 响应式设计 */
@media (max-width: 768px) {
  .dev-tools-panel {
    width: calc(100vw - 32px);
    max-width: 320px;
  }
}

/* 深色模式支持 */
@media (prefers-color-scheme: dark) {
  .panel-content {
    background: #1a1a1a;
    border-color: #333;
  }
  
  .panel-header,
  .status-section {
    background: #2a2a2a;
    border-color: #333;
  }
  
  .panel-title,
  .metric-value {
    color: #fff;
  }
  
  .status-label,
  .shortcuts-title {
    color: #ccc;
  }
  
  .metric-label,
  .shortcut-item {
    color: #999;
  }
  
  .shortcuts-info {
    border-color: #333;
  }
}
</style>
